/**
* Copyright (c) 2021-2022 Hailo Technologies Ltd. All rights reserved.
* Distributed under the LGPL license (https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt)
**/
#pragma once
#include <map>
namespace common
{
    static std::map<uint8_t, std::string> coco_ninety_classes = {
        {0, "unlabeled"},
        {1, "person"},
        {10, "traffic light"},
        {11, "fire hydrant"},
        {13, "stop sign"},
        {14, "parking meter"},
        {15, "bench"},
        {16, "bird"},
        {17, "cat"},
        {18, "dog"},
        {19, "horse"},
        {20, "sheep"},
        {2, "bicycle"},
        {21, "cow"},
        {22, "elephant"},
        {23, "bear"},
        {24, "zebra"},
        {25, "giraffe"},
        {27, "backpack"},
        {28, "umbrella"},
        {31, "handbag"},
        {32, "tie"},
        {33, "suitcase"},
        {3, "car"},
        {34, "frisbee"},
        {35, "skis"},
        {36, "snowboard"},
        {37, "sports ball"},
        {38, "kite"},
        {39, "baseball bat"},
        {40, "baseball glove"},
        {41, "skateboard"},
        {42, "surfboard"},
        {43, "tennis racket"},
        {4, "motorcycle"},
        {44, "bottle"},
        {46, "wine glass"},
        {47, "cup"},
        {48, "fork"},
        {49, "knife"},
        {50, "spoon"},
        {51, "bowl"},
        {52, "banana"},
        {53, "apple"},
        {54, "sandwich"},
        {5, "airplane"},
        {55, "orange"},
        {56, "broccoli"},
        {57, "carrot"},
        {58, "hot dog"},
        {59, "pizza"},
        {60, "donut"},
        {61, "cake"},
        {62, "chair"},
        {63, "couch"},
        {64, "potted plant"},
        {6, "bus"},
        {65, "bed"},
        {67, "dining table"},
        {70, "toilet"},
        {72, "tv"},
        {73, "laptop"},
        {74, "mouse"},
        {75, "remote"},
        {76, "keyboard"},
        {77, "cellphone"},
        {78, "microwave"},
        {7, "train"},
        {79, "oven"},
        {80, "toaster"},
        {81, "sink"},
        {82, "refrigerator"},
        {84, "book"},
        {85, "clock"},
        {86, "vase"},
        {87, "scissors"},
        {88, "teddy bear"},
        {89, "hair drier"},
        {8, "truck"},
        {90, "tooth brush"},
        {9, "boat"}};
}