FROM repo-docker.int.hailo.ai/hailo_repo_init_cpu_ub22:hrt

ENV TAPPAS_WORKSPACE=/local/workspace/tappas

WORKDIR ${TAPPAS_WORKSPACE}

COPY --chown=${USER}:${GROUP} . .

RUN sudo chown ${USER}:${GROUP} ${TAPPAS_WORKSPACE}

RUN sudo apt-get update && \
    ${TAPPAS_WORKSPACE}/scripts/build_scripts/install_pkg_file.sh core/requirements/basic_plugins.pkg && \
    ${TAPPAS_WORKSPACE}/scripts/build_scripts/install_pkg_file.sh core/requirements/gstreamer_plugins.pkg

RUN sudo add-apt-repository -y ppa:oibaf/graphics-drivers && \
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

RUN pip3 install --upgrade pip setuptools wheel

RUN mkdir -p ${TAPPAS_WORKSPACE}/sources && \
    ${TAPPAS_WORKSPACE}/scripts/build_scripts/install_opencv.sh

RUN ${TAPPAS_WORKSPACE}/scripts/build_scripts/install_deb_pkg_for_cross_compile.sh